[package]
name = "sema"
version = "0.1.0"
edition = "2021"

[dependencies]
arena = { path = "../arena" }
ast = { path = "../ast" }
data_structures = { path = "../data_structures" }
errors = { path = "../errors" }
session = { path = "../session" }
range = { path = "../range" }
