[package]
name = "sema"
version = "0.1.0"
edition = "2021"

[dependencies]
arena = { path = "../arena" }
ast = { path = "../ast" }
errors = { path = "../errors" }
range = { path = "../range" }
session = { path = "../session" }
symbol = { path = "../symbol" }

