[package]
name = "lexer"
version = "0.1.0"
edition = "2021"

[dependencies]
errors = { path = "../errors" }
range = { path = "../range" }
session = { path = "../session" }
source = { path = "../source" }
symbol = { path = "../symbol" }
token = { path = "../token" }
