[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
ast = { path = "../ast" }
errors = { path = "../errors" }
lexer = { path = "../lexer" }
range = { path = "../range" }
session = { path = "../session" }
token = { path = "../token" }